### ISSUE TITLE
How to render multiple waveforms in one page correctly?

### ISSUE THREAD

**Issue by jimmyyao88** [michaeldzjap/waveplayer.js#19]
Hello Michael.

I'm trying to place multiple waveforms in a single page like soundcloud. 

But everytime I create a waveform it will also create a new waveplayer instance on page which means it will create multiple audio tag elements in page.I have 100+ instance in a single page, and it will increase RAM usage soon.
And use playlist  cannot display multiple waveform views in a single page. 
I'm wondering how to use a single audio tag(a global context) to make it display multiple waveform view. (to avoid CPU and RAM over usage).

THX!

**Comment by jimmyyao88** [comment]
The page looks like soundcloud stream feed.
<img width="860" alt="Screen Shot 2021-03-13 at 8 58 24 PM" src="https://user-images.githubusercontent.com/7344857/111031125-efbf5800-8440-11eb-90e8-20f3a7b01d80.png">

**Comment by michaeldzjap** [comment]
Yes, I understand your concerns @jimmyyao88. However, I don't think it is really possible to change this easily without considerable refactoring and rethinking some core design choices. I've had it in the back of my mind for a while now to do a thorough refactoring of _waveplayer.js_, but this won't happen any time soon. So unfortunately I don't think I'll be able to help you out much, at least not at this point in time.

**Comment by jimmyyao88** [comment]
@michaeldzjap Thx for ur reply. I will check the source code and try to refactor. Thank you for bring us this great library!
