### ISSUE TITLE
Request : Option to turn bars gradient on and off

### ISSUE THREAD

**Issue by thespice** [michaeldzjap/waveplayer.js#6]
As lovely as it is, and it is lovely, there may be some situations where having the option to turn the gradient off would be beneficial.

**Comment by michaeldzjap** [comment]
This could be a new option, yes. Should not be too hard to allow for.

**Comment by michaeldzjap** [comment]
This feature has been added in [v1.1.0](https://github.com/michaeldzjap/waveplayer.js/tree/v1.1.0).
